---
- name: Ensure chrony is installed.
  yum:
    name: chrony
    state: installed

- name: Copy chrony config file in place.
  template:
    src: chrony.conf.j2
    dest: /etc/chrony.conf
  notify: restart chronyd

# service
- name: Ensure chronyd is started and enabled to start at boot.
  service: name=chronyd state=started enabled=yes
